Working_directory: /remote/complex/piqv/plankton_rw/uvp6_missions
Project_to_clean: uvp6_sn000111lp/uvp6_sn000111lp_2023_rainer
Output_folder: uvp6_sn000111lp/rainer_clean
Project_name: uvp6_sn000111lp_2023_rainer
