Working_directory: /remote/complex/piqv/plankton_rw/uvp6_missions
Project_to_clean: uvp6_sn000002lp/uvp6_sn000002lp_2023_sea002_m519
Output_folder: uvp6_sn000002lp_clean
Project_name: uvp6_sn000002lp_2023_sea002_m519
